jari = input()
tinggi = input()
phi = 3.142857
volume = phi*(float(jari)*float(jari)) * float(tinggi)
luas = 2*phi*float(jari)*(float(jari) + float(tinggi))
keliling = 2*phi* float(jari)
print("Volume   = %.2f"%(volume))
print("Luas     = %.2f"%(luas))
print("Keliling = %.2f"%(keliling)) 