Nama =    input("Nama                   : ")
NIM =     input("NIM                    : ")
Paralel = input("Kelas Paralel          : ")
TTL =     input("Tempat/Tanggal Lahir   : ")
Alamat =  input("Alamat                 : ")
Hobby =   input("Hobby                  : ")
NoHP =    input("No. HP                 : ")

print("Nama                   : ", Nama)
print("NIM                    : ", NIM)
print("Kelas Paralel          : ", Paralel)
print("Tempat/Tanggal Lahir   : ", TTL)
print("Alamat                 : ", Alamat)
print("Hobby                  : ", Hobby)
print("No. HP                 : ", NoHP)
